### ISSUE TITLE
NullPointerException at com.freshplanet.inapppurchase.utils.IabHelper.launchPurchaseFlow

### ISSUE THREAD

**Issue by TurboMask** [freshplanet/ANE-In-App-Purchase#44]
Many of our games on Google Play have crash reports related to this extension. Here is one full report:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{air.com.tutotoons.app.babyhouse/com.freshplanet.inapppurchase.activities.BillingActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
at android.app.ActivityThread.access$800(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.freshplanet.inapppurchase.utils.IabHelper.launchPurchaseFlow(Unknown Source)
at com.freshplanet.inapppurchase.utils.IabHelper.launchPurchaseFlow(Unknown Source)
at com.freshplanet.inapppurchase.activities.BillingActivity.onCreate(Unknown Source)
at android.app.Activity.performCreate(Activity.java:5231)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
... 11 more
`

**Comment by TurboMask** [comment]
Anyone investigating this bug? It still appears with new ANE.
