### ISSUE TITLE
getProductsInfo fails

### ISSUE THREAD

**Issue by caseyryan** [freshplanet/ANE-In-App-Purchase#63]
I'm trying to get products info from google play store by passing getProductsInfo an array like this:
["gold_10000", "gold_50000"], and the subscriptions array is empty (but I tried to pass there the same array as well). 
Even though I can easily buy those products. 
Android device monitor says this, right after I try to load infos:

01-25 01:18:37.905: W/System.err(13405):    at com.freshplanet.inapppurchase.functions.BaseFunction.getStringFromFREObject(Unknown Source)
01-25 01:18:37.905: W/System.err(13405):    at com.freshplanet.inapppurchase.functions.BaseFunction.getListOfStringFromFREArray(Unknown Source)
01-25 01:18:37.905: W/System.err(13405):    at com.freshplanet.inapppurchase.functions.GetProductsInfoFunction.call(Unknown Source)
01-25 01:18:37.905: W/System.err(13405):    at com.freshplanet.inapppurchase.functions.BaseFunction.getStringFromFREObject(Unknown Source)
01-25 01:18:37.905: W/System.err(13405):    at com.freshplanet.inapppurchase.functions.BaseFunction.getListOfStringFromFREArray(Unknown Source)
01-25 01:18:37.905: W/System.err(13405):    at com.freshplanet.inapppurchase.functions.GetProductsInfoFunction.call(Unknown Source)

I think that for some reason, freObject.getAsString() cannot parse these arrays. Or maybe I'm mistaken. 
Has anyone faced the same issue? Am I doing something wrong or is it a bug of the extension?

**Comment by caseyryan** [comment]
Sorry! There is no issue, it's totally my fault. Probably too tired.
The reason was that I used vararg as a parameter, but passed simple array as first argument. And it lead to something like [["gold_10000"]]. Of course this didn't work.
